export const FiltersActions = {
  DISPLAY_GRID: 'DISPLAY_GRID',
  DISPLAY_LIST: 'DISPLAY_LIST',
  UPDATE_FILTERS: 'UPDATE_FILTERS',
  FILTER_PRODUCTS: 'FILTER_PRODUCTS',
  UPDATE_SORT: 'UPDATE_SORT',
  CLEAR_FILTERS: 'CLEAR_FILTERS',
  SORT_PRODUCTS: 'SORT_PRODUCTS',
  SET_PRODUCTS: 'SET_PRODUCTS',
};
